### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ghost** [gmestanley/DNH-V#1]
Hello, gmestanley, I am really looking forward to the release of your work, but when will you compile a version? And can DNH-V be used for online multiplayer to play STG at the same time?

**Comment by gmestanley** [comment]
Hello, thank you for the comment! A release will be compiled when the code is completely buildable; currently, it is not in that state yet. If you want already compiled releases of Danmakufu with Netplay in them, check out the older repository of this project [DNH-Netplay](https://github.com/gmestanley/DNH-Netplay). And yes, it can be used for (peer-to-peer) multiplayer STGs that can be played online, as it uses [SFML](https://github.com/SFML/SFML)'s networking functions to provide that experience.
