### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ghost** [gmestanley/DNH-V#4]
Hello,gmestanley.I build the whole solution,but DnhViewer and FileArchiver have some problems that I can't build them.I found DNH-V is not compatible with ph3,but there is no game making tutorial for DNH-V or Danmakufu ph3.5 nf4,so I need some helps for develop a danmaku game.

**Comment by gmestanley** [comment]
Hello! Once again I apologize for the late response.
DnhViewer and FileArchiver have been having issues for a while now; their problem was that a certain library file, zlib.lib, wasn't being included (DnhViewer had the additional problem of the Networking class' files not being included in it). The latest commits from [7dfc212](https://github.com/gmestanley/DNH-V/commit/7dfc212e4e5409dcd35033fe07e4f32c8f03d348) to [e970bf7](https://github.com/gmestanley/DNH-V/commit/e970bf7d735f4977ca456e77b940fa8768209fd0) solve the aforementioned issues, so now the whole solution is buildable. However I'm not sure if I can provide a build myself considering DnhViewer currently has broken text; I'll consider it.
As for game-making tutorials, ph3.5 just provides a list of new functions expecting you to use other existing tutorials for Danmakufu, but I do plan on making my own tutorial for it including new functions provided with DNH-V. I hope that's enough.
